src/i18n/I18n.js

`('${string}').trim().length > 0` will always be true.

Template literals require backticks

---

src/model/Model.js
test/unit/model/Model_spec.js

An attributeValue will be removed from the attributeValues array
when the value is set to ''(empty string), undefined or null.
We do allow false or 0 as they are allowed and will be changed to
"false" and "0" on the server side.

Modify the handling of attributeValues

---

test/setup/node.js
test/unit/api/api_spec.js

The global.FormData would be set to undefined when the tests are run
in watch mode. This would therefore make the FormData test fail on
each re-run after the initial run.

Reset the global.FormData on each test run.

---

src/d2.js
src/datastore/DataStore.js
test/unit/d2_spec.js
test/unit/datastore/DataStore_spec.js

Creating the singleton when evaluating the module would cause
problems. when trying to fake/mock the api for cases where fetch
might not be available or is mocked in the beforeEach of a test.
This also bring the retrieval of the dataStore in line with how it
works for e.g. SystemSettings.

Use static DataStore.getDataStore method for init

---

CHANGELOG.md
package.json
src/api/Api.js
src/api/__tests__/api.spec.js
src/datastore/__tests__/DataStore.spec.js

API requests no longer support `dataType` and `contentType` options, which were only kept for backward compatibility with jQuery. See CHANGELOG.md for migration steps.

Remove deprecated `dataType` and `contentType` request options

---

.codeclimate.yml

Text beginning with ** requires quotes (line 8) in order to parse. So, for consistency, added quotes around all values.
Also added exclude_paths at the root level to ensure that test files are never evaluated.

Fix parsing error in .codeclimate.yml

---

src/period/generators/__tests__/bi-monthly_spec.js
src/period/generators/__tests__/financial-april_spec.js
src/period/generators/__tests__/financial-july_spec.js
src/period/generators/__tests__/financial-october_spec.js
src/period/generators/__tests__/monthly_spec.js
src/period/generators/__tests__/quarterly_spec.js
src/period/generators/__tests__/six-monthly-april_spec.js
src/period/generators/__tests__/six-monthly_spec.js
src/period/generators/__tests__/weekly_spec.js
src/period/generators/__tests__/yearly_spec.js

While downloading the lib & running test, found a bunch of them broken due to hard coding 2017 as "current year" (which is not the case anymore).
Replaced them by calls to new Date().getFullYear() to get them running for the years to come.
Happy new year!

Use current year instead of hard coded '2017' to fix period tests

---

src/model/helpers/__tests__/json.spec.js
src/model/helpers/json.js

The favorites property will always be an array of strings, where the string is a userId.

Add 'favorites' as a non-embedded collection property for all model types

---

package.json
src/model/ModelCollectionProperty.js
src/model/__tests__/ModelCollectionProperty.spec.js

Enhanced isDirty() function on ModelCollectionProperty to by default also check for any dirty values inside the collection. This can be overridden by passing isDirty(false), and it will behave like the old way (only check for models added/removed from the collection).

ModelCollectionProperty isDirty to check for dirty values

---

src/model/helpers/json.js

When saving dataSetNotificationTemplates, an empty array is always returned as d2 think it's a collection. This should be sent "as-is" as an array.

Add dataSetNotificationTemplate as non-model-collection

---

src/api/Api.js
src/api/__tests__/api.spec.js

This feature enables editing interpretation comments, by updating the API endpoint through **d2.Api.getApi().update()**, with plain text strings.
JIRA ticket: https://jira.dhis2.org/browse/DHIS2-3430
PR: https://github.com/dhis2/dashboards-app/pull/191
The payload when editing an interpretation comment will always be a string, but the update() function performs the PUT request with the default option application/json - resulting in stringify'ing a string, leaving extra quotation marks (which the Regex will fail to filter out).
The tests for .update() have also been changed to expect the body as a string, and option sent with content.type: text/plain (The tests still call the functions with an object as payload parameter, which is consistent with the documentation).

Feature/.update() - send payload data with text/plain option present [DHIS2-3430]

---

src/analytics/AnalyticsRequestPropertiesMixin.js
src/analytics/__tests__/AnalyticsRequest.spec.js

This method allows to pass an object with query string parameters to pass to the analytics request.
Handy for setting multiple parameters at once, instead of chaining each .with* method.

Analytics request .withParameters() method

---

src/analytics/AnalyticsRequestPropertiesMixin.js

DEFAULT is not a valid value for aggregationType in the analytics request, but is what is stored in the Analytic Object, so skip in case it comes around.

Fix aggregationType DEFAULT handling

---

.travis.yml
jsdoc.json
package.json
yarn.lock

- Uses deploy-build to build and publish d2
- Deploy from the build directory like we do for other libs
- Bundle documentation with the build so we have version-to-version docs

Setup travis in the new way

---

src/model/helpers/json.js

This is to allow `interpretation.created` to end up in the JSON object when `chartModel.toJSON` is called.

Treat interpretations as non collection for chart models

---

package.json

The development dependency `babel-jest` was incorrectly added to `dependencies`.  This doesn't play well with `react-scripts` >= 2.0 which requires singular `babel-jest` dependency at version `23.6.0`:
```
The react-scripts package provided by Create React App requires a dependency:
"babel-jest": "23.6.0"
Don't try to install it manually: your package manager does it automatically.
However, a different version of babel-jest was detected higher up in the tree:
```

fix: Move development dependencies to devDependencies

---

src/period/__tests__/parser_spec.js
src/period/helpers.js
src/period/parser.js

The d2-period-parser is being used internally by the d2-ui PeriodPicker component, so this needs support for BiWeekly periods too.
BiWeekly and Weekly periodTypes have a lot in common. So to keep things DRY, I extracted some logic from `weeklyMatcherParser` and moved it into `computeWeekBasedPeriod`. It is perhaps not the most elegant solution, because `computeWeekBasedPeriod` has to return a lot of properties to the calling function. So if you see any room for improvement there, that would be nice.

Period parser support for bi-weekly periods

---

CHANGELOG.md

In looking back at the previous changelog note I'm a bit confused as to why we put the breaking change of enforcing encoded API requests under 30.1.0. It was also backported 28.4.0 and 31.3.0. Bit confusing.
So to anyone reviewing this, the sudden jump from 30.1.0 to 31.5.0 is not a single version bump, but because the version bumps in between are not in the changelog.

chore: update changelog in preparation of 31.5.0

---

README.md
package.json
src/d2.js
webpack.config.dev.js
yarn.lock

D2 was published as a library that could be used by including it as a `<script src="...">` on a page as well. The question is if we still want to support that, and if anyone still actually does that. It's pretty outdated and I don't think anyone actually really does this. This PR removes that section from our build.

breaking: remove webpack browser bundle

---

src/period/__tests__/parser.spec.js
src/period/parser.js

> Add type to returned period object, so a periodType can be easily derived from a periodId
This PR has to do with the new PeriodPicker component:
- PeriodPicker will show a drop-down for `periodType` and `period`
- The period field contains a string that should be parseable by the period parser, i.e. "2017W4"
- If some record already has a value on its period field, then I want populate the both drop-downs with the correct values
- So this means I get a `periodId` and I want to be able to work out which `periodType` that id corresponds with.
- And adding a property here seemed to be to most sensible thing to do....

feat: period-parser

---

src/system/SystemSettings.js
src/system/__tests__/SystemSettings.spec.js

There is not so much code to review, but quite a lot of context to explain:
- I found this issue in `d2` when working on [DHIS2-6860](https://jira.dhis2.org/browse/DHIS2-6860) in the settings-app.
- What happens is the following:
1.   When the app is initialised a call to `d2.system.settings.all()` is done
2.  Now we have access to `d2.system.settings.settings`. (Quite likely apps are not meant to access that property directly, but since `.get` returns a promise, I can imagine it is convenient to do so.)
3.  Now, if any setting-field in the settings-app changes, a call to `d2.system.settings.set(key, value)` is done.
4.  Before this PR, what would happen, is that the entire cached object is removed, which makes `typeof d2.system.settings.settings === 'undefined'`
5. After this PR, the …

fix(system-settings): update cache instead of deleting

---

src/analytics/AnalyticsBase.js
src/analytics/__tests__/AnalyticsBase.spec.js

This PR will have the following result:
When you add `withIncludeNumDen(false)` to a request instance, and you then call `d2.analytics.aggregate.get(req)` the get request for the actual data will now also have `includeNumDen === false`.
Before this fix, it would default to true.
I've also included some tests.
Let me know if this should be merged or closed, and I'll take it from there.

Fix: respect request instance include num den in get

---

src/analytics/AnalyticsRequestBase.js
src/analytics/__tests__/AnalyticsRequestBase.spec.js

Fixes [DHIS2-10722](https://jira.dhis2.org/browse/DHIS2-10722)
Due to the encoding being done in d2 request, having it here causes a
double encoding problem, which throws an error and stops the request
from being fired.
After the fix:
https://user-images.githubusercontent.com/150978/111803241-28db4a80-88cf-11eb-9a58-1d513aac8bf3.mov

fix: remove encoding of query string for analytics requests DHIS2-10722

---

src/analytics/AnalyticsRequest.js

Fixes [DHIS2-9789](https://jira.dhis2.org/browse/DHIS2-9789)
"Backported" from https://github.com/dhis2/analytics/pull/776
DV 35.x uses analytics from `d2`, while later version use analytics from `@dhis2/analytics`. This "backports" the fix done in analytics.

fix: only pass fixed dimensions as dimension for data value sets

---

src/model/helpers/json.js

This fixes so that userGroupAccesses and userAccesses send `access` and other nested fields when saved. This is used in maintenance app mainly. 
Related to these fixes https://github.com/dhis2/maintenance-app/pull/1812 and https://github.com/dhis2/maintenance-app/pull/1817

feat(json): treat access collection as non-model collections

---

src/api/Api.js
src/datastore/BaseStoreNamespace.js
src/datastore/__tests__/DatastoreNamespace.spec.js
src/datastore/__tests__/UserDatastoreNamespace.spec.js

Fix for [https://jira.dhis2.org/browse/DHIS2-12135](https://jira.dhis2.org/browse/DHIS2-12135)
Previously, `api.update()` inferred the content-type from the type of the `value`, so when it was a string, content-type was set to `text/plain`. However, there was no way to override this, like for the `api.post`-method. It's a bit weird to me that these methods do not follow the same api/use shared logic. Nevertheless, I did not want to introduce a breaking change here due to this repo being in "maintenance"-mode. So that is why I included the previous functionality of setting to `text/plain` if headers are not set, and the type of the value is a `string`.
Updates the `update()` in `DataStoreNameSpace` to override the headers so that it always PUTs `json`.

fix(api): allow Content-Type override for update()
